- name: Restart SSH
  ansible.builtin.systemd:
    name: ssh
    state: restarted

- name: Restart Fail2Ban
  ansible.builtin.systemd:
    name: fail2ban
    state: restarted

- name: Reload UFW
  community.general.ufw:
    state: reloaded
